# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
---
version: 2

# https://stackoverflow.com/questions/48991482/run-circleci-2-0-build-using-several-jdks
shared: &shared
  working_directory: ~/repo
  environment:
    # Customize the JVM maximum heap limit
    MAVEN_OPTS: -Xmx3200m
  steps:
    - checkout

    - run:
        name: Install Clojure
        command: |
          wget -nc https://download.clojure.org/install/linux-install-1.10.3.855.sh
          chmod +x linux-install-1.10.3.855.sh
          sudo ./linux-install-1.10.3.855.sh
             
    # Download and cache dependencies
    # - restore_cache:
    #    keys:
    #      - v1-dependencies-{{ checksum "pom.xml" }}
    #      # fallback to using the latest cache if no exact match is found
    #      - v1-dependencies-

    - run: mvn dependency:go-offline
    - run: mvn install --quiet -DskipTests=true

    # - save_cache:
    #    paths:
    #      - ~/.m2
    #    key: v1-dependencies-{{ checksum "pom.xml" }}
    # run tests!
    - run: mvn test
    # lint (especially reflection warnings)
    - run: clojure -M:test:eastwood

jobs:
  java-8:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    <<: *shared

  java-13:
    docker:
      - image: circleci/openjdk:13-jdk-buster
    <<: *shared

workflows:
  version: 2
  work:
    jobs:
      - java-8
      - java-13
